Clarify the L2 voting process
snowpackjs/astro pull request #1079
Opened 2021-08-10 20:36 UTC by matthewp

2021-08-10 20:41 UTC, FredKSchott commented on GOVERNANCE.md
> +- Committer contributor membership: discussion conducted via a thread with all existing L2 contributors. Thread will be deleted once a decision is made.
- mention simple vs. overwhelming majority
- actually, everything added here feels relevant to both membership voting, not just committer. Does it make more sense to add this to the existing bullet point as "~core~ contributor membership" and then also remove the point about private messaging for both? I'd be +1 on that change.

2021-08-10 21:05 UTC, FredKSchott commented
LGTM! Remember that governance changes require a majority approval before merging + 3 day window.

2021-08-10 21:46 UTC, natemoo-re requested changes
Just cleaning up some wording

2021-08-10 21:46 UTC, natemoo-re commented on GOVERNANCE.md
> +- Contributor membership (L2 and L3): discussion via a temporary channel with qualified contributors for up to 3 days. overwhelming majority (over 70%) vote conducted by privately messaging a steward
```suggestion
- Contributor membership (L2 and L3): discussion conducted via a temporary Discord channel open to qualified contributors for up to 3 days. Acceptance requires an overwhelming majority (over 70%) vote conducted by privately messaging a steward. Funneling both assenting and dissenting votes directly through stewards allows for anonymity when discussing the merits of a potential contributor.
```

2021-08-11 20:12 UTC, natemoo-re approved these changes

2021-08-11 23:42 UTC, FredKSchott commented
@drwpow waiting for your vote to merge!

2021-08-14 18:53 UTC, FredKSchott commented
3 days have elapsed, @drwpow automatically marked as abstaining. 
@natemoo-re @matthewp @FredKSchott marked as approved. 

PR approved!

2021-08-14 18:53 UTC, merged