[lit] Automatically detect `customElements.define()` and `@customElement()` calls
snowpackjs/astro pull request #1722
Opened 2021-11-01 17:48 UTC by natemoo-re

## Changes

- Removes the need for manual `export const tagName = "my-element";`
- Supports `customElements.define("my-element", MyElement)` calls
- Supports Lit's `@customElements("my-element")` decorator

## Testing

Manually, updating the `framework-lit` example

## Docs

Will do be before merge.

2021-11-01 17:53 UTC, natemoo-re commented on examples/framework-lit/src/components/Counter.js
> -export const tagName = 'my-counter';
These can be removed, they're no longer needed!

2021-11-01 17:53 UTC, natemoo-re commented on examples/framework-lit/src/components/Counter.js
> +customElements.define('my-counter', Counter);
Our custom Lit Vite plugin will pick up on this and add an `export const __astroTagName = "my-counter"` export

2021-11-01 17:53 UTC, natemoo-re commented on examples/framework-lit/src/components/Greeting.ts
> +@customElement('simple-greeting')
Our custom Lit Vite plugin will also pick up on the `@customElement()` Lit decorator!

2021-11-01 17:53 UTC, natemoo-re commented on examples/framework-lit/src/components/Test.js
>  customElements.define(tagName, CalcAdd);
This also works!

2021-11-01 17:53 UTC, natemoo-re commented on packages/renderers/renderer-lit/vite-plugin-lit.js
> +      const result = s.toString();
This is pretty much it. If we find `@customElement("my-element")` or `customElements.define("my-element", MyElement)`, we add the export while respecting sourcemaps.

2021-11-01 17:53 UTC, natemoo-re commented on packages/renderers/renderer-lit/vite-plugin-lit.js
> +  })
Parse with `acorn`.

2021-11-01 19:10 UTC, matthewp commented
This is definitely very cool, but I think we should talk about this with the core team. There are some tradeoffs here, not having to opt-in is nice, parsing every JS file is unfortunate (it is opt-in via using this off-by-default renderer though, so that's a bit better).

2021-11-01 19:11 UTC, matthewp requested changes
Let's talk about this with the core team before merging.

2021-11-01 19:59 UTC, natemoo-re commented
Thanks @matthewp! Totally agree, looking forward to chatting about it on the RFC call!

2021-11-02 21:17 UTC, natemoo-re commented
Going to close this and reopen as an RFC, per the RFC call.

2021-11-02 21:17 UTC, closed without merging