Update deploy.md
snowpackjs/astro pull request #1781
Opened 2021-11-09 22:38 UTC by Steve-B-Murphy

Add Layer0 information to deploy.md

## Changes
This adds Layer0 to the Astro DOCS 'Deploy on the web' page

## Testing
No code was created so no testing needed. All information was copied from the approved https://docs.layer0.co/guides/astro page.

## Docs
This adds Layer0 to the Astro DOCS 'Deploy on the web' page

2021-11-09 23:21 UTC, jasikpark requested changes

2021-11-09 23:21 UTC, jasikpark commented on docs/src/pages/guides/deploy.md
> +# Then, add Layer0 to your MkDocs site:
```suggestion
# Then, add Layer0 to your Astro site:
```

2021-11-09 23:21 UTC, jasikpark commented
lgtm otherwise!

2021-11-10 19:55 UTC, Steve-B-Murphy reviewed
I agree with the suggested changes.

2021-11-10 20:07 UTC, jasikpark approved these changes

2021-11-10 20:07 UTC, merged

2021-11-10 20:15 UTC, Steve-B-Murphy commented
Hi @jasikpark, thanks for working with me. When can I see the changes on the Astro Docs [deploy](https://docs.astro.build/es/guides/deploy/) page?

2021-11-10 20:20 UTC, jasikpark commented
Currently, Astro Docs are tied to Astro releases, so <https://docs.astro.build> deploys from `latest`, and normally `next.docs.astro.build` would contain the upcoming docs changes, but we're still integrating v0.21 w/ the docs site to make it function! 

I'm hoping we can publish the docs separately sometimes though: https://github.com/snowpackjs/astro/issues/1779