Fix script resolution
snowpackjs/astro pull request #438
Opened 2021-06-14 23:01 UTC by drwpow

## Changes

⚠️ requires merge of #437, as this extends that resolution test

Fixes #104.

## Testing

Adds tests

## Docs

No docs needed

2021-06-14 23:02 UTC, drwpow commented on packages/astro/src/build.ts
> +                  throw new Error(`${buildState[id].srcPath.href}: could not find "${path.basename(url)}"`);
@matthewp when I try and display a helpful error message here, this is what I end up seeing:

![Screen Shot 2021-06-14 at 16 22 29](https://user-images.githubusercontent.com/1369770/121969777-39fef080-cd32-11eb-8524-a12f07e654b9.png)

It has something to do with how this is being passed to the logger, but I couldn’t figure this out. How can we fix this?

(to recreate this, simply try and run `astro build` with an asset that doesn’t exist, such as `<script src="foo.js">`)

2021-06-14 23:52 UTC, FredKSchott commented on packages/astro/test/fixtures/astro-resolve/src/pages/scripts.astro
> +    <!-- type="module" but no leading "." -->
shouldn't we add a test for:

```
    <!-- type="module" but leading "." -->
    <script type="module" src="./relative.js"></script>
```

2021-06-14 23:57 UTC, FredKSchott requested changes
Can we talk about this one as well before merging? It feels odd to resolve some attributes but not others, and I had assumed we were taking a stance of: "whatever HTML you give us, is what we send to the page". Sounds like maybe I missed a Discord chat?

Both this and #437 just feel like a really big step to be taking and I just want to make sure that we've thought this through before going down this path.

2021-06-15 15:53 UTC, drwpow commented
> Can we talk about this one as well before merging? It feels odd to resolve some attributes but not others, and I had assumed we were taking a stance of: "whatever HTML you give us, is what we send to the page". Sounds like maybe I missed a Discord chat?
> 
> Both this and #437 just feel like a really big step to be taking and I just want to make sure that we've thought this through before going down this path.

Like #437 this also isn’t a change in behavior; we’ve done this for a while. This just fixes a bug where we unintentionally transformed paths that had a `.` but didn’t if they ommitted that (the original issue). Sure, we can talk about changing this for sure, but we do need to fix the bugs first, and both these PRs are only bugfixes.

2021-06-15 19:58 UTC, FredKSchott submitted a review, later dismissed

2021-06-15 21:06 UTC, merged