New Props API
snowpackjs/astro pull request #515
Opened 2021-06-22 21:08 UTC by natemoo-re

## Changes

Astro's parser was originally forked from the Svelte parser, so we inherited their syntax for component props. This PR updates to a new, Astro-specific props syntax.

See #139, #309

**Previously**
```jsx
---
export let title: string | undefined;
---
```

**New Props API**
```jsx
export interface Props {
  title?: string;
}
const { title } = Astro.props as Props;
```

## Testing

TBD

## Docs

TBD

2021-06-24 15:02 UTC, matthewp commented
@natemoo-re Code looks pretty good to me, need any help pushing this along?

2021-06-24 16:16 UTC, natemoo-re commented
@matthewp Just need to go through and update our examples! I'm doing that now.

2021-06-24 19:41 UTC, matthewp commented on docs-www/src/layouts/Main.astro
> +const { content } = Astro.props;
i like this so much better, no magic.

2021-06-24 19:45 UTC, matthewp requested changes
Code looks good. Can you add a changeset and make this a minor change? This will break existing apps so want to make sure it doesn't go through as a patch on accident.

2021-06-24 19:59 UTC, FredKSchott commented
This looks great! Can we add a warning if you try to define props the old way? it should be as easy as scanning the exports, and only allowing `createCollection` and `Props`. And then we can remove this workaround whenever we tackle the idea of a component export.

2021-06-24 20:03 UTC, matthewp approved these changes
Great changeset!

2021-06-24 22:36 UTC, natemoo-re commented
@FredKSchott warning added!

<img width="1061" alt="Screen Shot 2021-06-24 at 5 33 59 PM" src="https://user-images.githubusercontent.com/7118177/123340894-a1772600-d512-11eb-8262-09096bb1131d.png">

2021-06-24 22:48 UTC, merged

2021-06-24 23:05 UTC, duncanhealy reviewed
compileExpressionSafe got changed by pr https://github.com/snowpackjs/astro/pull/522  to transpileExpressionSafe

2021-06-24 23:05 UTC, duncanhealy commented on packages/astro/src/compiler/codegen/index.ts
> +    let transpiledScript = compileExpressionSafe(script, { state, compileOptions, location });
```suggestion
 let transpiledScript = transpileExpressionSafe(script, { state, compileOptions, location });
```

2021-06-25 02:13 UTC, jasikpark commented on packages/astro/src/compiler/codegen/index.ts
> +    let transpiledScript = compileExpressionSafe(script, { state, compileOptions, location });
Yup. This is failing to build for me D: